# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-13 07:34
from __future__ import unicode_literals

from django.db import migrations, models
import indee.models


class Migration(migrations.Migration):

    dependencies = [
        ('indee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='imagefile',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='document',
            name='name',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='docfile',
            field=models.FileField(upload_to='documents/%Y/%m/%d', validators=[indee.models.validate_pdf]),
        ),
    ]
